release:
  name: CD
  needs: build
  runs-on: ubuntu-latest
  environment: dev

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    # DEBUG: ver qué existe realmente dentro de dist/
    - name: Show dist tree
      run: |
        echo "=== dist tree ==="
        ls -R dist

    - name: Deploy-Dev
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        # IMPORTANTE: pon wrangler explícito para evitar interpretaciones raras
        command: wrangler deploy dist/practice4/index.js --name ancient-recipe-9c7b --compatibility-date 2026-03-01 --compatibility-flags=nodejs_compat --assets dist/client